"""initial schema

Revision ID: 8a9fceee2584
Revises: 
Create Date: 2026-09-15 02:35:11.825647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9fceee2584'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('party_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_logs_created_at', 'action_logs', ['created_at'], unique=False)
    op.create_index('ix_action_logs_party_id', 'action_logs', ['party_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'notified', 'seated', 'canceled', 'no_show', name='partystatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('estimated_wait', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('seated_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('party_size >= 1 AND party_size <= 12', name='chk_party_size'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_parties_status', 'parties', ['status'], unique=False)
    op.create_index('ix_parties_token', 'parties', ['token'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('occupied_by_party_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('capacity >= 1 AND capacity <= 20', name='chk_table_capacity'),
    sa.ForeignKeyConstraint(['occupied_by_party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tables_occupied', 'tables', ['is_occupied'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tables_occupied', table_name='tables')
    op.drop_table('tables')
    op.drop_table('settings')
    op.drop_index('ix_parties_token', table_name='parties')
    op.drop_index('ix_parties_status', table_name='parties')
    op.drop_table('parties')
    op.drop_index('ix_action_logs_party_id', table_name='action_logs')
    op.drop_index('ix_action_logs_created_at', table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
